version: "2.1"

services:

  ms-sql-server:
    build:
      context: ./ms-sql-server
      dockerfile: ./dockerfile
    ports:
      - 1438:1433

  web-site:
    build:
      context: ./web-site
      dockerfile: ./dockerfile
    ports:
      - 9000:8842
