version: "2.1"

services:
  web-site:
    extends:
      file: ./web-site/docker-compose.yml
      service: web-site
  ms-sql-server:
    extends: 
      file: ./ms-sql-server/docker-compose.yml
      service: ms-sql-server
